### ISSUE TITLE
Reference should link to TR35

### ISSUE THREAD

**Issue by davedelong** [subdigital/nsdateformatter.com#12]
TR35 is the part of the unicode spec that deals with locale-specific stuff.

Having a link to the date formatter section (which is what `NSDateFormatter` uses) would be very convenient: http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns

**Comment by subdigital** [comment]
Apologies for taking so long, but I just added a link in the Reference section. Thanks!
