### ISSUE TITLE
Format Error on Year

### ISSUE THREAD

**Issue by cluster626** [subdigital/nsdateformatter.com#16]
The following formats will give the same result on the website:

MMM dd yyyy hh:mm a
and
MMM dd YYYY hh:mm a

However, they behave differently if you test them in Xcode playground

For example, with this date string: "Mar 28 2018 12:28 PM"

If converted to Date using the first formatter format, the Date will be 'Mar 28, 2018 at 12:28 PM'
but with the second formatter format, the same string becomes 'Dec 24, 2017 at 12:28 PM'

**Comment by subdigital** [comment]
I'm somewhat stumped on this.  Looking at the unicode reference, `Y` is used for week-of-year based calendars and shouldn't be used to represent the year in a Gregorian calendar, however it does return the year when going from `Date` to `String`.

The only difference I can think of is the version of Swift, and I would be very surprised if there were recent changes in Foundation that would cause this.

I will be updating the site to Vapor 3 eventually and I'll revisit this issue to see if I get similar results when I get to doing that.

**Comment by subdigital** [comment]
It's been a while, I'm going to close this issue. The format `YYYY` really shouldn't be used, as it is almost certainly not what most people need when working with dates. On certain input, `YYYY` will give you a different result than `yyyy` and is the source of a lot of confusion (and bugs).
