### ISSUE TITLE
Add support for fractional seconds

### ISSUE THREAD

**Issue by ejmartin504** [subdigital/nsdateformatter.com#7]
Love the site! My humble feature request is for fractional seconds, which are supported by NSDateFormatter. 

For example, the string "2016-07-21T15:18:49.339Z" is properly formatted using this format string: "yyyy-MM-dd'T'HH:mm:ss.SSSZ" (Note the capital "S" used for fractional seconds!)

**Comment by ilyawiz** [comment]
The site at nsdateformatter.com still doesn't reflect this change + actually using SSS in the format adds zeroes instead of seconds/milliseconds
