### ISSUE TITLE
Arabic locales do not work

### ISSUE THREAD

**Issue by Lopdo** [subdigital/nsdateformatter.com#8]
I tried with default values for date and format string. I set locale to ar_AE and all I got was 

RESULT
...

which I believe is loading. I suppose it crashed somewhere along the way and I never got to see the result

**Comment by subdigital** [comment]
I believe that this is related to encoding on the Javascript side. There's a similar issue with French dates that include accented characters.

**Comment by subdigital** [comment]
This does work now, the issue was captured in detail in #9 .
