### ISSUE TITLE
Response length issue for non-ASCII characters

### ISSUE THREAD

**Issue by hybridcattt** [subdigital/nsdateformatter.com#9]
I have noticed a bug that some specific locales are not supported. Examples are `ru_*` or `ar_*`.

I did some investigation on my side and it seems that the problem lies somewhere between Jay and Frank (no pun intended)

This is how a normal response looks:

`{"date_string":"2016-10-17T20:17:55+02:00","result":"17 October 2016","status":"ok"}
`

And this is how it looks for Russian locale:

`{"date_string":"2016-10-17T20:17:55+02:00","result":"17 октября 2016","status
`
or
`{"date_string":"2016-10-17T20:17:55+02:00","result":"17 окт. 2016","status":"o
`

And in Arabic:

`{"date_string":"2016-10-17T20:17:55+02:00","result":"١٧ أكتوبر ٢٠١٦","s
`

As you can see, the result seems to be cut off, usually in the same place for the same string length.
The amount of missing characters is exactly the difference between character and byte count of the string (3/6 for russian "окт" and 12/22 for arabic - 10 missing) - you can do some quick checking here https://mothereff.in/byte-counter 

I believe #8 describes the same issue. 

PS. I saw your talk at PragmaConf, very cool. 
I have tried to look into this myself (well, find which one of the dependencies is faulty - your own code works fine, I checked), but unfortunately you've been using one of the early versions of Swift 3, so nothing compiles on the current stable release. 

Hope this helps. If you upgrade to stable Swift 3.0, I'll be happy to help.

**Comment by subdigital** [comment]
Thanks so much for this detailed writeup!  I will probably be rewriting this for Swift 3 using Kitura, and so I _hope_ that this issue will be addressed then.

**Comment by subdigital** [comment]
I believe this has been addressed now.  (I upgraded to swift 3/Vapor a little while ago)
